// Auto-generated code. Do not edit.
namespace myTiles {
    //% fixedInstance jres blockIdentity=images._tile
    export const transparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile36 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile48 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile57 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile58 = image.ofBuffer(hex``);

}
// Auto-generated code. Do not edit.
